version: "3"
services:
 app:
  build: .
  depends_on:
   - postgres
  environment:
   DEV_DATABASE_URL: postgres://postgres:@nhEm1nha@postgres:5432/live-tutor
   NODE_ENV: development
   DATABASE_DIALECT: postgres
   PORT: 3000
   JWT_SECRET: anhem1nha
   JWT_EXPIRATION_MINUTES: 30
   JWT_REFRESH_EXPIRATION_DAYS: 30
  command: bash -c "npx sequelize db:migrate && npm start"
  ports:
   - "3000:3000"
  volumes:
   - .:/app/
   - /app/node_modules

 postgres:
  image: postgres:13.1
  ports:
   - "5432:5432"
  environment:
   POSTGRES_USER: "postgres"
   POSTGRES_PASSWORD: "@nhEm1nha"
   POSTGRES_DB: "live-tutor"
