const languages = [
  'andorra',
  'armenia',
  'aahrain',
  'angola',
  'australia',
  'bangladesh',
  'albania',
  'anguilla',
  'austria',
  'belarus',
  'algeria',
  'antigua & barbuda',
  'azerbaijan',
  'american samoa',
  'argentina',
  'bahamas',
  'benin',
  'gernamy',
  'mexico',
  'bolivia',
  'brazil',
  'brunei',
  'myanmar',
  'south africa',
  'south korea',
  'hugary',
  'hong kong',
  'spain',
  'nauru',
  'nepal',
  'india',
  'indonesia',
  'new Zealand',
  'nigeria',
  'taiwan',
  'english',
  'cuba',
  'france',
  'vietnamese',
  'zambia',
  'united kingdom',
  'united states',
];

const specialties = [
  'foreign languages',
  'marketing',
  'office infomation',
  'design',
  'business',
  'health care',
  'infomation technology',
];

module.exports = {
  languages,
  specialties,
  up: () => Promise.resolve(),
  down: () => Promise.resolve(),
};
